project:
  type: website

website:
  title: "Yin-Yun Li"
  navbar:
    background: dark
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: about.qmd
      # - text: CV
      #   href: cv.pdf
      # - text: Notes
      #   href: notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true